apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artifact-service-api
  description: Artifact Service APIs
  tags:
    - postman
    - internal
spec:
  type: openapi
  lifecycle: production
  owner: team-user
  system: core-platform
  definition:
    $text: ./arifact-openapi.yaml
