apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth-service-api
  description: Auth Service APIs
  tags:
    - postman
    - internal
spec:
  type: openapi
  lifecycle: production
  owner: team-user
  system: core-platform
  definition:
    $text: ./auth-openai.yaml
